spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lianyt1994/config-only-a-demo
          username: lianyt1994
          password: liant1126
          default-label: master
      profile: dev

  datasource:
    url: jdbc:mysql://localhost:3306/deliver_ad
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    ip-address: localhost
mybatis:
  typeAliasesPackage: com.xdd.entity
  mapperLocations: classpath:mapper/*.xml

server:
  port: 12345
