spring:
  datasource:
    url: jdbc:mysql://localhost:3306/deliver_ad
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  typeAliasesPackage: com.xdd.entity
  mapperLocations: classpath:mapper/*.xml

