spring:
  datasource:
    url: jdbc:mysql://localhost:3306/deliver_ad
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  typeAliasesPackage: com.xdd.entity
  mapperLocations: classpath:mapper/*.xml

AdUser:
  id: 2
  name: 3
  feature: 4
